version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase-if-necessary"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "America/Los_Angeles"
    reviewers:
      - "amalitsky"
    labels:
      - "dependency"
      - "dependabot"
    open-pull-requests-limit: 7
